---
- hosts: all
  tasks:
    - name: Installing nginx web server
      apt: pkg=nginx state=installed update_cache=false
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started